project:
  type: website

website:
  title: "SML 301 Spring 2025"
  navbar:
    right:
      - text: sessions
        href: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cerulean
    css: styles.css



