project:
  type: website

website:
  title: "SML 301 Slides"
  description: "Lecture slides for SML 301, Spring 2025 semester"
  navbar:
    right:
      - blog.qmd

format:
  html:
    theme: cerulean



