{
  "hash": "e73d8b83fa3ddb07abbf9163c6c8b0aa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"6: Decision Trees\"\nauthor: \"Derek Sollberger\"\ndate: \"2026-09-23\"\nformat:\n  html:\n    toc: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Session 6: Decision Trees\n\n## Learning objectives:\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n- Start to form decision trees\n- Partition decision space\n- Explore Shannon entropy\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n![decision tree](penguins_tree_example.png)\n:::\n\n::::\n\n# Scenario: Palmer Penguins\n\n::::: {.panel-tabset}\n\n## Penguins!\n\n![Palmer Penguins](lter_penguins.png)\n\n## Predictors\n\n![the bills](culmen_depth.png)\n\n## Categorical Prediction\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n:::::\n\n\n# First Tree\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-warning}\n## DCP 1\n:::\n\n## First Choice\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Next Choice\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Cutoff\n\nIf we *cutoff* the tree-making process here, we have trained the tree model as follows\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Data Split\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\n## Metrics\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Truth\nPrediction  Adelie Chinstrap Gentoo\n  Adelie       109         2      0\n  Chinstrap      2        43      0\n  Gentoo         0         4     89\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining accuracy: 0.9679\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting accuracy: 0.881\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n# Another Tree\n\n## Categorical Prediction\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## First Choice\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Next Choice\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## Metrics\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Truth\nPrediction  Adelie Chinstrap Gentoo\n  Adelie       107        49      0\n  Chinstrap      0         0      0\n  Gentoo         4         0     89\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining accuracy: 0.7871\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting accuracy: 0.75\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n# Activity: Literature Methods\n\nWe will look at the concluding paragraphs for some of the most influential papers in the history of machine learning:\n\n::: {.callout-tip}\n## Suggested Papers\n\n### AlexNet\n\n* ImageNet Classification with Deep Convolutional Neural Networks (2012)\n\n### GANs\n\n* General Adversarial Nets (2014), Goodfellow et al.\n\n### GPT\n\n* Improving Language Understanding by Generative Pre-Training (2018) aka GPT, Radford, Narasimhan, Salimans, and Sutskever\n\n### TensorFlow\n\n* TensorFlow: A system for large-scale machine learning (2016), Abadi et al.\n\n### XGBoost\n\n* XGBoost: A Scalable Tree Boosting System (2016), Chen and Guestrin\n\n### Word2Vec\n\n* Efficient Estimation of Word Representations in Vector Space (2013), Mikolov, Chen, Corrado, and Dean\n:::\n\n\n\n# Several Splits\n\n::::: {.panel-tabset}\n\n## Motivation\n\nTo avoid bias (part of the bias-variance trade-off), we should employ multiple training-testing splits.\n\n## 1\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Truth\nPrediction  Adelie Chinstrap Gentoo\n  Adelie       101        55      4\n  Chinstrap      0         0      0\n  Gentoo         3         1     85\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining accuracy: 0.747\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting accuracy: 0.7738\n```\n\n\n:::\n:::\n\n\n:::\t\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## 2\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Truth\nPrediction  Adelie Chinstrap Gentoo\n  Adelie       108        48      0\n  Chinstrap      0         0      0\n  Gentoo         1         1     91\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining accuracy: 0.7992\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting accuracy: 0.7143\n```\n\n\n:::\n:::\n\n\n:::\t\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## 3\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Truth\nPrediction  Adelie Chinstrap Gentoo\n  Adelie       113        50      2\n  Chinstrap      0         0      0\n  Gentoo         0         1     83\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining accuracy: 0.7871\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting accuracy: 0.7976\n```\n\n\n:::\n:::\n\n\n:::\t\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## 4\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Truth\nPrediction  Adelie Chinstrap Gentoo\n  Adelie       109        50      1\n  Chinstrap      4         6      0\n  Gentoo         0         1     78\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining accuracy: 0.7751\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting accuracy: 0.8571\n```\n\n\n:::\n:::\n\n\n:::\t\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## 5\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Truth\nPrediction  Adelie Chinstrap Gentoo\n  Adelie       105        41      0\n  Chinstrap      4         7      0\n  Gentoo         5         0     87\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining accuracy: 0.7992\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting accuracy: 0.7381\n```\n\n\n:::\n:::\n\n\n:::\t\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::::\n\n## CV Error\n\nAfter $k$ **folds** of cross-validation, we compute the cross-validation accuracy by taking the average of the accuracy values.\n\n$$\\text{CV error} = \\displaystyle\\frac{0.7738 + 0.7143 + 0.7976 + 0.8571 + 0.7381}{5} \\approx 0.7762$$\n\n:::::\n\n\n::: {.callout-warning}\n## DCP 2\n:::\n\n\n# Choice Order\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\n## Entropy\n\nFrom information theory, we borrow the notion of **Shannon entropy** to get a sense of how well a choice can separate classes in the data. \n\n$$E = -\\sum_{i=1}^{J} p_{i} \\log_{2} p_{i}$$\n\n* $J$ groups in the categorical response variable\n* $p_{i}$: probability of being in group $i$\n* logarithm base does not matter (since we will simply be seeking a maximum)\n\n## Categorical Predictors\n\n::::: {.panel-tabset}\n\n### Island\n\nIn the `penguins` data, we have a distribution in the `island` variable.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Biscoe     Dream Torgersen \n      163       123        47 \n```\n\n\n:::\n:::\n\n\nAmong $n = 333$ penguins in total, the entropy for this choice is\n\n$$E = -\\left(\\frac{163}{333}\\right)\\log_{2} \\left(\\frac{163}{333}\\right) - \\left(\\frac{123}{333}\\right)\\log_{2} \\left(\\frac{123}{333}\\right) - \\left(\\frac{47}{333}\\right)\\log_{2} \\left(\\frac{47}{333}\\right)$$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The entropy for this variable is: 1.4339\"\n```\n\n\n:::\n:::\n\n\n### Sex\n\nIn the `penguins` data, we have a distribution in the `sex` variable.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nfemale   male \n   165    168 \n```\n\n\n:::\n:::\n\n\nAmong $n = 333$ penguins in total, the entropy for this choice is\n\n$$E = -\\left(\\frac{165}{333}\\right)\\log_{2} \\left(\\frac{165}{333}\\right) - \\left(\\frac{168}{333}\\right)\\log_{2} \\left(\\frac{168}{333}\\right)$$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The entropy for this variable is: 0.9999\"\n```\n\n\n:::\n:::\n\n\n### Choice\n\nBetween these categorical variables, `island` presents more information entropy than `sex`, so `island` could be used before `sex` for the entire data set (i.e. the entropy comparison could change later under a smaller subset of data).\n\n:::::\n\n\n## Numerical Predictors\n\n::::: {.panel-tabset}\n\n### formula\n\nWe need to update our formula for Shannon entropy for a numerical variable.  Here, I suggest computing the probabilities across a discretization of the numerical variable.\n\n$$\\begin{array}{rcl}\n  E & = & -\\displaystyle\\text{max}_{z} \\sum_{i=1}^{J} P(X_{i} \\leq z)\\log_{2}P(X_{i} \\leq z) \\\\\n  ~ & ~ & - \\sum_{i=1}^{J} P(X_{i} > z)\\log_{2}P(X_{i} > z)\n\\end{array}$$\n\n$$z \\in \\mathbb{N}, \\quad \\text{min}(X) < z < \\text{max}(Z)$$\n\nTo avoid taking logarithms of zero probabilities, we can apply a *Laplace adjustment*\n\n$$P(X_{i} < z) = \\frac{(\\text{count}_{i} < z) + 1}{\\text{total count} + 1}$$\n\n### bill depth\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -1.53757237950003\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 16\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n### bill length\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -1.56651763573707\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 42\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n### body mass\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -1.54388648974619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 4800\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n### flipper length\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -1.36723424446796\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 207\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n:::::\n\n\n# First Node\n\nOut of the numerical predictors, we have the most entropy from the `flipper_length_mm` variable, so that becomes our first node in the decision tree.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\n# Second Node\n\nWe now focus on one of leaves (`flipper_length_mm` < 206)\n\n\n::: {.cell}\n\n:::\n\n\n::::: {.panel-tabset}\n\n### bill depth\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -1.76335733794724\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 21\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-67-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n### bill length\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -0.825053496962708\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 45\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-69-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n### body mass\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -1.68294309563248\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 3175\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-71-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n### flipper length\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nmax entropy: -1.61011231175945\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nthreshold: 186\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-73-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n:::::\n\nOut of the numerical predictors, we have the most entropy from the `bill_length_mm` variable, so that becomes our next node in the decision tree.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06_decision_trees_files/figure-html/unnamed-chunk-74-1.png){width=672}\n:::\n:::\n\n\n\n\n# Universal Approximation\n\n::: {.callout-tip}\n## Ideal Model\n\nIf we can produce a function that truly represents the data, then perfect predictions would come from the function evaluation.\n:::\n\n## Experiment:\n\n$$f(x) = x^{3} - x^{2} - 2x$$\n\n* sample: 100 data points $(x_{i}, f(x_{i}))$ in $[-5, 5]$\n* training set: 70 data points\n* test set: 30 data points\n\n![discrete approximation](step_approx.png)\n\n* image source: [Future Learn](https://www.futurelearn.com/info/courses/an-introduction-to-machine-learning-in-quantitative-finance/0/steps/297285)\n\n::: {.callout-warning}\n## Overfitting\n\nWhen we are improving (by metric) in modeling over the training data and yet are performing worse with the test data, we are probably **overfitting** the data.\n\nThat is, the machine learning is memorizing the training data, but is not generalizing well to new data.\n\n:::\n\n::: {.callout-warning}\n## DCP 3\n:::\n\n\n\n# Quo Vadimus?\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n* due this Friday:\n\n    - Precept 3\n    - Literature Report (quick essay)\n    - Pick Group Partners (survey)\n\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n![agentic parenting](agentic_parenting.png)\n:::\n\n::::\n\n\n# Footnotes\n\n::: {.callout-note collapse=\"true\"}\n\n## (optional) Additional Resources and References\n\n* Plotting Decision Trees](https://www.spsanderson.com/steveondata/posts/2023-09-29/index.html) in R with `rpart` and `rpart.plot` by Steven P Sanderson II\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] yardstick_1.4.0      workflowsets_1.1.1   workflows_1.3.0     \n [4] tune_2.1.0           tidyr_1.3.2          tailor_0.1.0        \n [7] recipes_1.3.3        purrr_1.2.2          parsnip_1.6.0       \n[10] modeldata_1.5.1      infer_1.1.0          dials_1.4.4         \n[13] scales_1.4.0         broom_1.0.13         tidymodels_1.5.0    \n[16] rsample_1.3.2        rpart.plot_3.1.5     rpart_4.1.27        \n[19] palmerpenguins_0.1.1 ggtext_0.1.2         GGally_2.4.0        \n[22] ggplot2_4.0.3        dplyr_1.2.1         \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1    timeDate_4052.112   farver_2.1.2       \n [4] S7_0.2.2            fastmap_1.2.0       digest_0.6.39      \n [7] timechange_0.4.0    lifecycle_1.0.5     survival_3.8-6     \n[10] magrittr_2.0.5      compiler_4.6.1      rlang_1.2.0        \n[13] tools_4.6.1         yaml_2.3.12         data.table_1.18.4  \n[16] knitr_1.51          labeling_0.4.3      htmlwidgets_1.6.4  \n[19] xml2_1.6.0          DiceDesign_1.10     RColorBrewer_1.1-3 \n[22] withr_3.0.3         nnet_7.3-20         grid_4.6.1         \n[25] sparsevctrs_0.3.6   future_1.70.0       globals_0.19.1     \n[28] MASS_7.3-65         cli_3.6.6           rmarkdown_2.31     \n[31] generics_0.1.4      otel_0.2.0          rstudioapi_0.19.0  \n[34] future.apply_1.20.2 commonmark_2.0.0    stringr_1.6.0      \n[37] splines_4.6.1       parallel_4.6.1      vctrs_0.7.3        \n[40] hardhat_1.4.3       Matrix_1.7-5        jsonlite_2.0.0     \n[43] litedown_0.10       listenv_1.0.0       gower_1.0.2        \n[46] glue_1.8.1          parallelly_1.48.0   ggstats_0.14.0     \n[49] codetools_0.2-20    stringi_1.8.7       lubridate_1.9.5    \n[52] gtable_0.3.6        tibble_3.3.1        furrr_0.4.0        \n[55] pillar_1.11.1       htmltools_0.5.9     ipred_0.9-15       \n[58] lava_1.9.2          R6_2.6.1            evaluate_1.0.5     \n[61] lattice_0.22-9      markdown_2.0        backports_1.5.1    \n[64] gridtext_0.1.6      class_7.3-23        Rcpp_1.1.2         \n[67] prodlim_2026.03.11  xfun_0.57           pkgconfig_2.0.3    \n```\n\n\n:::\n:::\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\t\n:::\n\n::: {.column width=\"10%\"}\n\t\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n::::: {.panel-tabset}\n\n\n\n:::::",
    "supporting": [
      "06_decision_trees_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}